services:
  - type: web
    name: manybot-kz
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: FIREBASE_SECRET
        sync: false
      - key: WEBHOOK_URL
        sync: false
